n1 = int(input('Digite um Valor: '))
n2 = int(input('Digite outro Valor: '))
print(f'A soma vale {n1+n2:.3f}')
print(f'A subtração é {n1-n2:.3f}')
print(f'A multiplicação é {n1*n2:.3f}')
print(f'A divisão é {n1/n2:.3f}')
print(f'A divisão inteira é {n1//n2:.3f}')
print(f'A potência é {n1**n2:.3f}')
print(f'O resto da divisão é {n1%n2:.3f}')